sudo: false
language: node_js
node_js:
- '4.0'
notifications:
  slack:
    secure: ZAmybqOneqv38xDIf1ZVFfAN+IHne4cxUbi5fnJYYgMMi6k+SUh8gZed78ZRzrdhPcgrkgQh9CHCbxJEkPoE/M9pMpORwQP1wOOvlvWPJXBNtQZMdwIf6nQBwKE0tYeTnAgO+lc19ZhilygivU9rhmBYG/xMiFMA6QlvQBp66vFjOsKCCp77dOw45Si5uCSC+YDhFzD6ucfEuSR7z0UMRK+88zKa86CPJEg9G9rxK8nk4YlcuMhHxjhdTWyPSJdEO+Vpl+Pvr8LG6tgKVj0hj8qzi11cR835l4+Nlokt6RiKiMmXnWqVkk9RYP/7npmXWSM5DmqFp8d0SrJ0glifYou9PJ+p6k7RDFfeWlIWT1ohaflTlRjZ4t5t3sMezCsSxl+Sbrc4cg7PHyz1MosXQW0tYmwTS8st/nET7LQWcZeXPWn35u5GAp2bmPFx5icam6PEoQ6qKvuvWRj9bHkfF1zAJCUoA6T0+VYCIYkBI5HU9of2FcIfcsiClEzBMWDTpEr3wGehzSC7XWVqphOAKIsLgLxytO9QDnEZjrIQF5JhrEdfkC6oIS7PdMi7qwawBC7zybzpwpJLxttp3tpDCqx1ygHJd48J7EqtQJ9W5CqQUUrxc9DJz89Wfx9JN93sjM0RVx3cJjiTUlGluBBaqtfx0pBjGU5FvNRB3EHGA24=
